### ISSUE TITLE
How to disable logging in System.err?

### ISSUE THREAD

**Issue by leonamp** [junrar/junrar#109]
Hi. We are receiving this information in System.err:

```
[ESMTPS004] WARN com.github.junrar.Archive - Support for rar version 5 is not yet implemented!
[ESMTPS004] WARN com.github.junrar.Archive - exception in archive constructor maybe file is encrypted, corrupt or support not yet implemented
com.github.junrar.exception.UnsupportedRarV5Exception
        at com.github.junrar.Archive.readHeaders(Archive.java:353)
        at com.github.junrar.Archive.setChannel(Archive.java:198)
        at com.github.junrar.Archive.setVolume(Archive.java:778)
        at com.github.junrar.Archive.<init>(Archive.java:148)
        at com.github.junrar.Archive.<init>(Archive.java:177)
        ....
```

Is it possible to disable this logging?

**Comment by gotson** [comment]
Junrar uses SLF4J for logging, refer to their manual on how to configure it on your end.

**Comment by leonamp** [comment]
Thank you so much!
