### ISSUE TITLE
On attempt to extract archive RAR5 the archive is locked

### ISSUE THREAD

**Issue by Alister71** [junrar/junrar#28]
On attempt to extract rar archive version RAR5 the archive is locked.
Version 3.1.0, call:
> File arch = new File(archive);
File dest = new File(destination);
Junrar.extract(arch, dest);
> 
Exception stack:
> Support for rar version 5 is not yet implemented!
exception in archive constructor maybe file is encrypted, corrupt or support not yet implemented
com.github.junrar.exception.RarException: unsupportedRarArchive
	at com.github.junrar.Archive.readHeaders(Archive.java:282) 
	at com.github.junrar.Archive.setFile(Archive.java:153) 
	at com.github.junrar.Archive.setVolume(Archive.java:631) 
	at com.github.junrar.Archive.<init>(Archive.java:123) 
	at com.github.junrar.Archive.<init>(Archive.java:100) 
	at com.github.junrar.Junrar.createArchiveOrThrowException(Junrar.java:91) 	
at com.github.junrar.Junrar.extract(Junrar.java:33)
> 
On attempt to delete the archive, the  exception is thrown:
> java.nio.file.FileSystemException: The process cannot access the file because it is being used by another process 
>

**Comment by theobisproject** [comment]
@Alister71 Thanks for noting the issue. I will have a look at the problem.
