### ISSUE TITLE
CrcErrorException

### ISSUE THREAD

**Issue by ixiDev** [junrar/junrar#68]
**Describe the bug**
He there .
I am trying to extract some rar files  [here](https://shamela.ws/books/1510/151016.rar) is an  example 
The file was successfully extracted but i got this error 

```
com.github.junrar.exception.CrcErrorException
	at com.github.junrar.Archive.doExtractFile(Archive.java:591)
	at com.github.junrar.Archive.extractFile(Archive.java:531)
	at com.github.junrar.LocalFolderExtractor.extract(LocalFolderExtractor.java:52)
	at com.github.junrar.Junrar.tryToExtract(Junrar.java:180)
	at com.github.junrar.Junrar.extractArchiveTo(Junrar.java:154)
	at com.github.junrar.Junrar.extract(Junrar.java:54)
	at com.github.junrar.Junrar.extract(Junrar.java:46)
	at ixidev.shamela.data.filedownloader.FileDownloaderKtTest.extractRarFile(FileDownloaderKtTest.kt:73)
	at java.lang.reflect.Method.invoke(Native Method)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at androidx.test.internal.runner.junit4.statement.RunBefores.evaluate(RunBefores.java:80)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
	at androidx.test.internal.runner.TestExecutor.execute(TestExecutor.java:56)
	at androidx.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:395)
	at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:2204)
```

And here is my code is an Instrumented test on Android studio 

```kotlin
    @Test
    fun extractRarFile() {
        val bookId = 151016
        val appContext = InstrumentationRegistry.getInstrumentation().targetContext
        val inputStream = appContext.assets.open("$bookId.rar")
        val tempFolder = File(appContext.cacheDir, "$bookId")
        tempFolder.deleteOnExit()
        tempFolder.mkdir()
        Junrar.extract(inputStream, tempFolder)
        val extract = tempFolder.list()!!
        assertEquals(extract.size, 1)
    }
```
**Expected behavior**
The rar file contain a file with Arabic name, I thing the error comes from here
**File**
[rar file](https://shamela.ws/books/1510/151016.rar) 

**Environment (please complete the following information):**
 - OS: Android studio & Ubuntu , Android 10
 - Junrar version: [7.4.0]

Thanks

**Comment by gotson** [comment]
Hello, the problem does not come from the file name, but from the archive itself. The CRC for that file is incorrect upon extraction. Repackaging the same file in another RAR will not produce the CRC exception, despite the CRC being the same (you can check with `unrar vt <archive.rar>`.

**Comment by ixiDev** [comment]
Thanks @gotson  ,60% of file was extracted successfully but i don't know how to fix this CRC exception . Do u have any idea or suggestion please ?

**Comment by gotson** [comment]
I can't rally tell whether it's a problem with the archive or with the junrar code to be honest.

Do you have issues like this with many files, or just that one?

If it's a single file I would advise you to repackage it, using the official unrar utility or other software.

**Comment by ixiDev** [comment]
@gotson i have problem on all files that's coming from this site , i can't repacking it it's a lot of files . anyway thanks for support .
I am using 7z-Zip library it's working now.
Thanks.
