### ISSUE TITLE
com.github.junrar.exception.CrcErrorException during extracting of archive

### ISSUE THREAD

**Issue by AlexandrKozlovskiy** [junrar/junrar#74]
I have rar archive (http://qsp.su/index2.php?option=com_sobi2&sobi2Task=dd_download&fid=460&format=html) When i try to extract it on android:

```java
    public static boolean unrar(Context context, DocumentFile rarFile, File gameDir) {
        try (InputStream in = context.getContentResolver().openInputStream(rarFile.getUri())) {
            try (Archive archive = new Archive(in)) {
                FileHeader fileHeader;
                while ((fileHeader = archive.nextFileHeader()) != null) {
                    final FileHeader fh = fileHeader;
                    extractEntry(
                            fh.getFileName(),
                            fh.isDirectory(),
                            gameDir,
                            out -> archive.extractFile(fh, out));
                }
                return true;
            }
        } catch (Exception ex) {
            logger.error("Failed to extract a RAR archive", ex);
            return false;
        }
    }

    private static void extractEntry(
            String entryName,
            boolean entryDir,
            File gameDir,
            ThrowingStreamWriter writer) throws Exception {
        String normEntryName = entryName.replace("\\", "/");
        if (entryDir) {
            createDirectories(gameDir, removeTrailingSlash(normEntryName));
            return;
        }
        File parentDir = getParentDirectory(gameDir, normEntryName);
        String filename = getFilename(normEntryName);
        File file = createFile(parentDir, filename);
        try (FileOutputStream out = new FileOutputStream(file)) {
            writer.accept(out);
        }
    }

    @FunctionalInterface
    private interface ThrowingStreamWriter {
        void accept(FileOutputStream stream) throws Exception;
    }
}
```
I get an exception:

```
02-20 01:39:42.903 32078   431 E Quest Player:ArchiveUtil: com.github.junrar.exception.CrcErrorException
02-20 01:39:42.903 32078   431 E Quest Player:ArchiveUtil:  at com.github.junrar.Archive.doExtractFile(Archive.java:594)
02-20 01:39:42.903 32078   431 E Quest Player:ArchiveUtil:  at com.github.junrar.Archive.extractFile(Archive.java:534)
```

Please fix this issue,because winrar for windows extract it without any problems.

**Comment by gotson** [comment]
Your file has a CRC error on file `The Warlock of Firetop Mountain.qsp`, the expected CRC and computed CRC don't match. The file is damaged.



> because winrar for windows extract it without any problems

Maybe because you ticked "Keep Broken Files" ?
